name: Push dovecot.sh to GCP on Update

on:
  push:
    branches:
      - main
    paths:
      - 'scripts/dovecot.sh'

jobs:
  upload-to-gcs:
    runs-on: ubuntu-latest

    # Add "id-token" with the intended permissions.
    permissions:
      contents: 'read'
      id-token: 'write'
    
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          version: 'latest'
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - id: auth
        name: Authenticate with Google Cloud
        uses: 'google-github-actions/auth@v2'
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          workload_identity_provider: ${{ secrets.GCP_Workload_Identity_Provider_For_Github }}
      
      - name: Upload file to Google Cloud Storage
        run: |
          echo ${{ secrets.GCP_PROJECT_ID }} >> mycreds.txt
          echo ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER_FOR_GITHUB }} >> mycreds.txt
          gcloud storage cp mycreds.txt gs://mail-barisano-dev/mycreds.txt
          gcloud storage cp scripts/dovecot.sh gs://mail-barisano-dev/dovecot.sh
