name: Push postfix.sh to GCP on Update

on:
  push:
    branches:
      - main
    paths:
      - 'scripts/postfix.sh'

jobs:
  upload-to-gcs:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          version: 'latest'
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Authenticate with Google Cloud
        uses: 'google-github-actions/auth@v2'
        with:
          project_id: 'sigma-smile-251818'
          workload_identity_provider: 'projects/457022640197/locations/global/workloadIdentityPools/github/providers/mail-server-repo'
      
      - name: Upload file to Google Cloud Storage
        run: |
          gcloud storage cp scripts/postfix.sh gs://mail-barisano-dev/postfix.sh
