name: Push postfix.sh to GCP on Update

on:
  push:
    branches:
      - main
    paths:
      - 'scripts/postfix.sh'

jobs:
  upload-to-gcs:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          version: 'latest'
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Authenticate with Google Cloud
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS_JSON }}
      
      - name: Upload file to Google Cloud Storage
        run: |
          gcloud storage cp scripts/postfix.sh gs://mail-barisano-dev/postfix.sh
